export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const LOGIN_USER_REQUEST = 'LOGIN_USER-REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

export const LOGOUT_USER = 'LOGOUT_USER'

export const LOGGED_IN_USER_REQUEST = 'LOGGED_IN_USER_REQUEST'
export const LOGGED_IN_USER_SUCCESS = 'LOGGED_IN_USER_SUCCESS'
export const LOGGED_IN_USER_FAIL = 'LOGGED_IN_USER_FAIL'
export const LOGGED_IN_USER_RESET = 'LOGGED_IN_USER_RESET'

// Article action types
export const FIRST_TWO_ARTICLE_REQUEST = 'FIRST_TWO_ARTICLE_REQUEST'
export const FIRST_TWO_ARTICLE_SUCCESS = 'FIRST_TWO_ARTICLE_SUCCESS'
export const FIRST_TWO_ARTICLE_FAIL = 'FIRST_TWO_ARTICLE_FAIL'

export const EIGHT_ARTICLES_REQUEST = 'EIGHT_ARTICLES_REQUEST'
export const EIGHT_ARTICLES_SUCCESS = 'EIGHT_ARTICLES_SUCCESS'
export const EIGHT_ARTICLES_FAIL = 'EIGHT_ARTICLES_FAIL'

export const TWO_ARTICLES_BOTTOM_REQUEST = 'TWO_ARTICLES_BOTTOM_REQUEST'
export const TWO_ARTICLES_BOTTOM_SUCCESS = 'TWO_ARTICLES_BOTTOM_SUCCESS'
export const TWO_ARTICLES_BOTTOM_FAIL = 'TWO_ARTICLES_BOTTOM_FAIL'

export const FEATURED_ARTICLES_REQUEST = 'FEATURED_ARTICLES_REQUEST'
export const FEATURED_ARTICLES_SUCCESS = 'FEATURED_ARTICLES_SUCCESS'
export const FEATURED_ARTICLES_FAIL = 'FEATURED_ARTICLES_FAIL'

// Slider action types
export const HERO_SLIDER_REQUIEST = 'HERO_SLIDER_REQUIEST'
export const HERO_SLIDER_SUCCESS = 'HERO_SLIDER_SUCCESS'
export const HERO_SLIDER_FAIL = 'HERO_SLIDER_FAIL'

export const UPCOMING_MATCHES_REQUIEST = 'UPCOMING_MATCHES_REQUIEST'
export const UPCOMING_MATCHES_SUCCESS = 'UPCOMING_MATCHES_SUCCESS'
export const UPCOMING_MATCHES_FAIL = 'UPCOMING_MATCHES_FAIL'
