export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const LOGIN_USER_REQUEST = 'LOGIN_USER-REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

export const LOGOUT_USER = 'LOGOUT_USER'

export const LOGGED_IN_USER_REQUEST = 'LOGGED_IN_USER_REQUEST'
export const LOGGED_IN_USER_SUCCESS = 'LOGGED_IN_USER_SUCCESS'
export const LOGGED_IN_USER_FAIL = 'LOGGED_IN_USER_FAIL'
export const LOGGED_IN_USER_RESET = 'LOGGED_IN_USER_RESET'
